- README.md
- src/babashka/process.clj
- test/babashka/process_test.clj
Thanks for starting Babashka project.
I like to add the option :dir so that the `process` function can be called from different directory.
Thanks
> Add :dir options to process builder

- src/babashka/process.clj
- test/babashka/process_test.clj
Add `:type :babashka.process/error` to the data of the exception thrown
on non-zero exit.
> feat: enable dispatch of errors based on ex-data type

- README.md
- src/babashka/process.clj
- test/babashka/process_test.clj
- This makes it more explicit
- This now always throws on a non-zero exit
> Rename wait -> check (#21)

- README.md
This looks really convenient, but I couldn’t help noticing a missing letter in the description.
> Fix small typographic error in project read me.

- src/babashka/process.clj
Following the discussion on slack.
The only keyword values allowed are `:string` and `:inherit`.
`:inherit` is explicitly not allowed when calling `copy` so it seems safe to constrain it
https://github.com/babashka/process/blob/4c6699d06b49773d3e5c5b4c11d3334fb78cc996/src/babashka/process.clj#L229-L234
> Case now checks :string instead of defaulting

- src/babashka/process.clj
- test/babashka/process_test.clj
This allows doing `(deref)` with a timeout.  Fix #50
> Add BlockingDeref to process

- doc/cljdoc.edn
Because it has cljc files, cljdoc assumes that babashka/process is a Clojure
and ClojureScript project. Explicitly telling cljdoc that this is a
Clojure only project will allow docs to build successfully on cljdoc.
Closes #56
> Add cljdoc config

- CHANGELOG.md
- README.md
- src/babashka/process.cljc
- src/babashka/process/pprint.clj
- test/babashka/process_test.cljc
closes #53 
- add `pprint/simple-dispatch` definition for `Process` records
- add tests that verify no exception is thrown when `pprint`ing a `Process`
- remove README section that describes the exception condition
I tried to do some of the housekeeping to maybe make life a little easier, but obviously feel free to tweak those or just throw them out. 
I added tests for Windows and non-Windows primarily for my convenience since I'm working primarily in Windows - then, I figured it's unlikely to hurt anything to have both tests, so I left them both there.
> define pprint/simple-dispatch for Process records

- CHANGELOG.md
- README.md
- src/babashka/process.cljc
- test/babashka/process_test.cljc
Pursuant to https://github.com/babashka/babashka/issues/1249, this change adds an option to side-effect the tokenized command vector.
I'm sort of torn on whether to join the strings together to call the fn on the command line string instead of the vector of tokens. I sort of think that would be the more common usage, but if someone wants the tokens, they'd need to re-split the string that we'd join together. 
The windows test assertions are a little uglier to account for potentially varying paths to `cmd`.
> add cmd-print-fn option to process fn

- src/babashka/process.cljc
Hi,
could you please review patch to mention clojure's standard streams in `process`'s docstring as per #88 discussion.
I also took the liberty to update a couple of docstrings so that their description starts with a summary sentence so as to be more appropriate for quickdoc's TOC.
Feel free to (completely) rewrite the contents at your discretion.
Thanks
> Update process' docstring to mention clojure standard streams

- src/babashka/process.cljc
- test/babashka/process_test.cljc
Hi,
could you please consider fix for `check` failure when the `:err` stream passed to process is a standard clj strem such as `*err*`. It addresses #90.
Thanks
> slurp `:err` in `check` only if it is an input stream

- src/babashka/process.cljc
- test/babashka/process_test.cljc
I saw a couple of options for detecting features in process.cljc and chose the more explicit one.
I'm not sure how to test pre-JDK8 behavior when `.isAlive` is not available. Does babushka/process explicitly support pre-JDK 8? If so, any recommendations on how to test?
> Add alive? function to expose java.lang.Process::isAlive

- test/babashka/process_test.cljc
A simple fix to allow the test to properly validate the flow.
> Use valid file path in process_test code

- .circleci/config.yml
- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- src/babashka/process.cljc
- test/babashka/process_test.cljc
New tests launch clojure to as part of testing capturing stderr. Adjusted CI to download clojure deps before running tests so we did not pollute stderr with clojure's `Downloading: org/clojure...` stderr messages.
Bumped GitHub action setup-clojure. Prior to bump installed clojure was not launching in GitHub Actions default Windows shell.
Closes #113
> Support redirecting stderr to stdout

- .github/workflows/ci.yml
Of note: setup-java task docs recommend switching from adopt distribution to temurin, so did that too.
Closes #114
> ci: address warnings from GitHub Actions

- .circleci/config.yml
- .github/workflows/ci.yml
- README.md
- script/test
- script/wd.clj
- test/babashka/process_test.cljc
Instead of launching os specific commands we now launch the os-agnostic wee dummy `test/wd.clj` script via babashka. It is designed to satisfy the needs of tests.
Examples of types of changes to launched processes:
- echo hello -> bb script/wd.clj :out hello
- ls -> bb script/wd.clj :ls .
- grep somestring -> bb script/wd.clj :grep somestring
- clojure -e some-expr -> bb script/wd.clj :out boo :err bah :exit 1
Replaced most uses of `cat` with `bb script/wd.clj :upper`, I felt that transforming the input offered more proof that the process was run successfully.
Because our wee dummy script allows us to define explicit output and behaviour, tests assertions are now also often more explicit.
Took care to keep the args syntax the same as the original test. (i.e. args as string vs vector of …
> test: include full coverage for windows

- deps.edn
Bumps `babashka/fs` to latest version. Passing CI tests.
> Update babashka/fs version to 0.4.18

- CHANGELOG.md
- deps.edn
- src/babashka/process.cljc
- test/babashka/process_test.cljc
Java `ProcessBuilder` abstracts, but does not fully generalize, behaviour across underlying OS support for process creation. In the case of Windows, it does not resolve a program relative to the specified working dir. This results in file process creation errors due to the program not being found. This change resolves this nuance.
Bump babashka/fs to get updates to `which`.
Update internal and undocumented program-resolver fn signature. Formerly it expected `program` now it expects map with key `:program` and optionally key `:dir`.
Rewrote dir opt unit tests for better coverage.
We should discover problems when run from babashka.process now rather than accidental coverage offered when running from babashka.
The `exec` function tests are still a work in progress, so did some manual testing …
> Resolve relative `program` to `:dir` on windows

- project.clj
fs was bumped in deps.edn but not project.clj
babashka.process still currently uses project.clj to release to clojars.
Addendum to #126 and #128.
> Bump fs in project.clj

- .circleci/config.yml
- .github/workflows/ci.yml
- .gitignore
- CHANGELOG.md
- bb.edn
- deps.edn
- doc/cljdoc.edn
- doc/dev.md
- script/circle_ci.clj
- script/test
- script/wd.clj
- src/babashka/process.cljc
- test-native/bb.edn
- test-native/deps.edn
- test-native/src/babashka/test_native/bb.edn
- test-native/src/babashka/test_native/run_exec.clj
- test/babashka/process/test_utils.clj
- test/babashka/process_exec_test.clj
- test/babashka/process_test.cljc
New bb tasks:
- clean - delete build work
- test:bb - runs all tests under babashka
- test:native - runs exec tests against native image of run_exec.clj
- test:jvm - (renamed from test) runs non-exec tests under jvm clojure
CI:
- GitHub Actions updated to run native image tests
- jobs renamed to match CircleCI naming convention
- CircleCI was doing a subset of GitHub Actions work, it now is a full reflection.
- added jdk install support in script/circle_ci.clj
- bootstrapping CI to be able to run bb and then scripting in bb is much more pleasant/maintainable than scripting in bash+Powershell
- used jdk install support even on linux, instead of trying to to select jdk via docker image. This made config cleaner, allowed for consitent jdk selection across OSes and had surprisingly little …
> Add test support for `exec`

- test/babashka/process_exec_test.clj
I seem to sometimes forget to follow coding style for test names. Fixed.
Addendum for #117
> new test names now all end in -test

- src/babashka/process.cljc
- test/babashka/process_exec_test.clj
I think this was fixed by 3f093b70e114ff8dc318f21dec01a7a2a2fe4fcc.
Added test and updated docstring.
Closes #125
> Ensure `exec` supports `:cmd` opt

- bb.edn
Now properly defaults to Clojure 1.11, was throwing.
Addendum for #117
> test:jvm task - fix default clj version handling

- README.md
- script/wd.clj
- src/babashka/process.cljc
- test/babashka/process_test.cljc
Add `:out :bytes` option for `process` which collects the process stdout into a byte array.  `:err :bytes` is also supported.
Closes #38.
> Support `:out :bytes`

- .circleci/config.yml
- .github/workflows/ci.yml
- script/circle_ci.clj
- test/babashka/process_exec_test.clj
Setup CIs to run native tests against both Oracle and Community variants.
Closes #144
> test: bump Graalvm to JDK 21

- script/circle_ci.clj
We use the disco API to discover JDKs on CircleCI. Using `version` instead of `jdk_version` seems to fix things.
> circleci: fix jdk download

- .circleci/config.yml
- .github/workflows/ci.yml
- script/circle_ci.clj
**circleci: configuring for Apple silicon**
I could not find a combination of an m1 `resource_class` and `xcode` that did not produce a "not available for your project" error from CircleCI. So I left out `resource_class` for now. Perhaps all will be good after Apple Silicon is the only supportted macos executor on June 29, 2024. I'll come back and check on this an open a new issue if necessary.
**circleci: jdk: infer os and architecture from host**
JDK architecture was hardcoded to x64 but this is not appropriate for our new Apple silicone hardware. We now infer architecture from host.
Figured might as well infer os from host as well.
Adjusted install dir name to include os and architecture to support testability and a potential future where one might, for example, install x64 on Apple …
> ci: drop testing of jdk8 on macos

- deps.edn
Clojure 1.12 is automatically picked up by `bb test:jvm :clj-all` which is what we use on CI.
Closes #159
> ci: test against clojure 1.12, bump 1.11 current

- README.md
- src/babashka/process.cljc
As discussed on Slack: https://clojurians.slack.com/archives/CLX41ASCS/p1718798012312359?thread_ts=1718774256.150799&cid=CLX41ASCS
**me**
> @borkdude, I reviewed the babashka/process docs on this, and they are pretty good, but I guess they could be reworded slightly to be clearer.
Also, I noticed :continue is described in README but not in any docstring. Would you like a small PR?
**you**
> yes please!
> docs: minor: update descriptions of `:continue`

- test/babashka/process_exec_test.clj
Can't tell you how I missed undoing a check against absolutized version of an exe, but glad babashka CI didn't miss it!
Addendum for #165
> Fix for testing from babashka project

- src/babashka/process.cljc
Thanks a lot for creating babashka/process , it is awesome and helps us a lot :partying_face: 
We found this edge case due to an OutOfMemory issue on one of our production servers. It only occurs after several days. We call process/shell three times per second. Below a suggestion for a potential fix.
> Fix: the shutdown hook should be removed when the process ends to avoid a memory leak.

- .github/workflows/ci.yml
- deps.edn
- project.clj
- resources/META-INF/native-image/babashka/process/reflect-config.json
- src/babashka/process.cljc
This will make the bb uberjar still run on other JVMS
> Refactor conditional method invocation to more robust approach
